name: Repository Health Check
on: push 
env: 
    FILE_PRESENT: NOT PRESENT
jobs:
     job1:
        runs-on: ubuntu-latest
        steps:
            - run: echo "start job"    
            - uses: actions/checkout@v4
            - run: ls
            - run: find . -name "README.md" >> $FILE_PRESENT
            - run: echo $FILE_PRESENT