name: Repository Health Check
on: push 
env: 
    FILE_PRESENT: NOT PRESENT
jobs:
     job1:
        runs-on: ubuntu-latest
        steps:
            - run: echo "start job"    
            - uses: actions/checkout@v4
            - run: ls
            - if: ${{! find . -name "README.md"}}
               exit 1
            - run: echo $FILE_PRESENT